# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.4

# Mod Properties
mod_version=1.0.0
maven_group=com.simplyag
archives_base_name=customizable-brightness

# Dependencies
fabric_version=0.144.4+26.1
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
